### ISSUE TITLE
considering user-defined NaNs

### ISSUE THREAD

**Issue by kasra-keshavarz** [ShervanGharari/EASYMORE#12]
Problem statement:
--------------------

I am trying to use `easymore` with a NetCDF file that it's NaNs values are defined as 32,768.

The issue is that `easymore` fails to consider a user-defined value for NaNs (or missing values). Therefore, the area averaged data is corrupted.

The shapefile used as the target and sample of such a NetCDF file is attached below for further discussion.

[05BB001_shapefile.zip](https://github.com/ShervanGharari/EASYMORE/files/6368408/05BB001_shapefile.zip)
[MOD16A2.006_500m_aid0001_05BB001.nc.zip](https://github.com/ShervanGharari/EASYMORE/files/6368406/MOD16A2.006_500m_aid0001_05BB001.nc.zip)

System details:
----------------

- Operating System: Windows 10 - 64-bit

- Python: 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

- EASYMORE: 0.0.0 (?)

**Comment by ShervanGharari** [comment]
greetings!
The netcdf file has _fill_values and also has some other large values (which are not fill_values) and are perhaps indicative of some conditions such as ice, snow, etc (please refer to the product). EASYMORE is not designed to handle time-varying NaN values (some points/grids may or may not have values over time).
However, there are many ways to get around this issue; here is my solution within the capabilities of EASYMORE. This solution also provides you with a better understanding of which points have data for a given time step.
```
# loading EASYMORE and other packages
from easymore.easymore import easymore
import numpy as np
import pandas as pd
import geopandas as gpd
from geopandas.tools import sjoin
from shapely.geometry import Point
from shapely.geometry.polygon import Polygon

# easymore settings
esmr = easymore()
esmr.case_name                = 'BOW_EVAPORATION_MODIS'
esmr.temp_dir                 = 'temporary/'
esmr.output_dir               = 'output/'
esmr.source_nc                = 'MOD16A2.006_500m_aid0001_05BB001.nc'
esmr.var_names                = ['PET_500m']
esmr.var_lon                  = 'lon'
esmr.var_lat                  = 'lat'
esmr.var_time                 = 'time'
esmr.target_shp               = '05BB001_WGS84.shp'

#creating the point for grid center and keep those points that are inside the catchment
esmr.NetCDF_SHP_lat_lon() # create mesh of lat lon
lat = np.array(esmr.lat_expanded); lat = lat.flatten()
lon = np.array(esmr.lon_expanded); lon = lon.flatten()
# data frame from points
df = pd.DataFrame()
df ['lat'] = lat
df ['lon'] = lon
df ['ID'] = np.arange(len(lat))+1
point = esmr.make_shape_point(df,'lon','lat') # create point shapefile for centroid of netcdf file
# get the points that are inside the shapefile 
#https://gis.stackexchange.com/questions/208546/check-if-a-point-falls-within-a-multipolygon-with-python
poly  = gpd.GeoDataFrame.from_file(esmr.target_shp) # basin 
pointInPolys = sjoin(point, poly, how='left')
grouped = pointInPolys.groupby('index_right')
shp_points_sub = shp_points.loc[grouped.groups[0.0]]
shp_points_sub.to_file('points_inside.shp')

# the target shapefile becomes the points that are inside the basin (shapefile) at center of each grid
esmr.target_shp               = 'points_inside.shp'

# execute EASYMORE
esmr.nc_remapper()
```
This returns a resulting nc file with 15257 elements over 597 time steps (the value of each grid inside the basin). You can then easily read the nc file variable as a data frame, replace the large values with 0 perhaps and report the mean of each time step as basin average. It also provides you with a better understanding of the periods each grid has values, missing or flagged.

**Comment by kasra-keshavarz** [comment]
Thanks very helpful.
