### ISSUE TITLE
expand_source_shape is incompatible with source shapefile that has center values on the lon = -180 and/or lon = 180 line

### ISSUE THREAD

**Issue by wknoben** [ShervanGharari/EASYMORE#17]
The logic in https://github.com/ShervanGharari/EASYMORE/blob/08b4792a45eea9f2eb2ce2c733600472fe4c5825/easymore/easymore.py#L772 does not work when the source shapefile has longitude values equal to -180 or 180 while that shapefile itself covers [-180,180].

**Comment by ShervanGharari** [comment]
This is removed in the new version of EASYMORE. the corrected version is under `develop` branch and need to be tested. hopefully there is no need to remove the source shapefile close to -180 now.
I will merge this to the `master` when tested and confirmed.

**Comment by ShervanGharari** [comment]
is solved in easymore version 0.0.2
