### ISSUE TITLE
Incorrect warning message: "acc" should be "dir"

### ISSUE THREAD

**Issue by wknoben** [ShervanGharari/EASYMORE#30]
https://github.com/ShervanGharari/EASYMORE/blob/28fd7cdf7cef7651c69890042dd87e8966d21bf7/easymore/easymore.py#L2265

**Comment by ShervanGharari** [comment]
I have removed all the `gdal` related functions as well as river network creation function from EASYMORE V.1.0.0, it can be added later into a more specialized package for river/lake fabric. Therefore I close this issue.
