### ISSUE TITLE
`gdal-config --version` command does not work on Windows

### ISSUE THREAD

**Issue by wknoben** [ShervanGharari/EASYMORE#32]
https://github.com/ShervanGharari/EASYMORE/blob/1cbda2292c1c999a25e424001ab3cb37b458394a/setup.py#L6

gdal-config is a Unix-only command: https://gdal.org/programs/gdal-config.html

Equivalent on Widnows would be:
```
> gdalinfo --version
GDAL 3.2.1, released 2020/12/29
```

**Comment by ShervanGharari** [comment]
Thank you, I don't have access to windows, can you test it by local installation and checking for win OS.
sth like this should be put into setup file:
```
from sys import platform
if platform == "linux" or platform == "linux2":
    version = subprocess.run(["gdal-config","--version"], stdout=subprocess.PIPE).stdout.decode() 
elif platform == "darwin":
    version = subprocess.run(["gdal-config","--version"], stdout=subprocess.PIPE).stdout.decode() 
elif platform == "win32":
    # command for windows
```

**Comment by ShervanGharari** [comment]
@wknoben Can you please check this part of the code on windows?
```
from setuptools import find_packages, setup
import subprocess
from sys import platform

def get_installed_gdal_version():
    try:
        if ('linux' in str(platform).lower()) or ('darwin' in str(platform).lower()):
            version = subprocess.run(["gdal-config","--version"], stdout=subprocess.PIPE).stdout.decode()
        elif ('win' in str(platform).lower()):
            version = subprocess.run(["gdalinfo","--version"], stdout=subprocess.PIPE).stdout.decode()
        version = version.replace('\n', '')
        version = "=="+version+".*"
        return version
    except FileNotFoundError as e:
        raise(""" ERROR: Could not find the system install of GDAL.
                  Please install it via your package manage of choice.
                """
            )

get_installed_gdal_version()
```
this should return sth like `'==3.3.1.*'`
I can then update this function in setup.py.
Thank you in advance!

**Comment by ShervanGharari** [comment]
@wknoben please take a look at `setup_fix` branch. Please take a look at the setup.py, see if you agree with the code and config there. Test please with a preferably new virtual env and `setup_fix` branch. sth like this after setting the virtual env and let me know:
```
# check if the code run smoothly given the example on the easymore github repo
cd # go to home
rm -rf EASYMORE
git clone https://github.com/ShervanGharari/EASYMORE.git
cd EASYMORE
git checkout setup_fixed
pip install .
cd examples
pip install --no-index jupyter
jupyter nbconvert Chapter1_E1.ipynb --to python
python Chapter1_E1.py
```
upon your successful test, I will put out version 0.0.4!

**Comment by ShervanGharari** [comment]
@wknoben version 0.0.4 is out with fixed setup.py for windows. you can test if you can successfully install easymore using `pip install easymore` and see if the fist example runs successfully on your PC. tnx!
