### ISSUE TITLE
Error while installation on Graham

### ISSUE THREAD

**Issue by MIsmlAhmed** [ShervanGharari/EASYMORE#56]
Hi Shervan et al.,

I was trying to install the EASYMORE package on Graham (following the steps outlined here: https://github.com/ShervanGharari/EASYMORE/tree/main/env#linux)  and I encountered an error while loading the package. The error was related to the `mpi` library `import error ompi_mpi_info_null` while loading the `netCDF4` library.

I fixed the problem by adjusting the required modules by loading  `python 3.9.6` and the latest `mpi4py`. I used the following command `module load python/3.9.6 scipy-stack/2022a mpi4py`

I also made sure to install easymore using `python -m pip install easymore` to ensure that I use the current python version (3.9.6) to install the compatible libraries.

EASYMORE is working fine after those tweaks (based on the test case).

**Comment by ShervanGharari** [comment]
The [link](https://github.com/ShervanGharari/EASYMORE/tree/main/env) is updated.

Upon your confirmation, I'll close this issue.

Thank you,

**Comment by MIsmlAhmed** [comment]
Thanks for your quick response and for updating the documentation.

You can close the ticket.
